@baseUrl = http://127.0.0.1:8000

####
GET {{ baseUrl }}

####
GET {{ baseUrl }}/api/events
Accept: application/json

####
GET {{ baseUrl }}/api/events/2
Accept: application/json

####
POST {{ baseUrl }}/api/events
Accept: : application/json
Authorization: Bearer 3|UuWEaKrM9guS1p4G6bU7reyg5CSiPNaxYvjiEkIwbaedff87
Content-Type: application/json

{
    "name": "first event",
    "start_time": "2023-07-01 15:00:00",
    "end_time": "2024-07-01 16:00:00"
}

####
PUT {{ baseUrl }}/api/events/56
Accept: : application/json
Authorization: Bearer 6|4cMp76Wlt8mDu1wxGRogtJiZ5DkpxgNo8cpMvI64c5eeaadc
Content-Type: application/json

{
    "name": "the name of this event got modified"
}

####
DELETE {{ baseUrl }}/api/events/209
Accept: : application/json
Authorization: Bearer 3|UuWEaKrM9guS1p4G6bU7reyg5CSiPNaxYvjiEkIwbaedff87

####
GET {{ baseUrl }}/api/events?include=user,attendees,attendees.user
Content-Type: application/json

####
POST {{ baseUrl }}/api/events?include=user,attendees
Content-Type: application/json

{
    "name": "first event",
    "start_time": "2023-07-01 15:00:00",
    "end_time": "2024-07-01 16:00:00"
}